language: ruby

os:
  - linux
  - osx

rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - jruby-9.2.5.0

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-9.2.5.0

notifications:
  email: false

env:
  global:
    - JRUBY_OPTS="--debug"
    - NO_IPV6_TESTS=1

script:
  - bundle exec rake build
  - bundle exec rake coveralls
