language: ruby

os:
  - linux
  - osx

rvm:
  - 2.5.1
  - 2.4.4
  - jruby-9.1.17.0

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - rvm: jruby-9.1.17.0

notifications:
  email: false

env:
  - NO_IPV6_TESTS=1

script:
  - bundle exec rake build
  - bundle exec rake coveralls
